Abraham/Abraham/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Abraham.Domain.Business.Interfaces;
using Abraham.Domain.Business.Services;
using Abraham.Domain.Data.Interfaces;
using Abraham.Domain.Data.Repositories;

namespace Abraham.Controllers
{
    public class ComputerController : Controller
    {
        private IComputerRepository _repository;
        private IComputerService _service;

        public ComputerController()
        {
            const string connectionString = @"server=192.168.11.70\SQLEXPRESS,1433;database=abraham;uid=sa;password=toto;Application Name=Homer";

            _repository = new ComputerRepository(connectionString);
            _service = new ComputerService(_repository);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form(int id)
        {
            var computer = _service.Get(id);
            return View(computer);
        }
    }
}

Abraham/Abraham/Controllers/ServiceTypeController.cs
using Abraham.Domain.Business.Interfaces;
using Abraham.Domain.Data.Interfaces;
using System.Web.Mvc;
using Abraham.Domain.Business.Services;
using Abraham.Domain.Data.Repositories;
using Abraham.Domain.Business.DTOs;

namespace Abraham.Controllers
{
    public class ServiceTypeController : Controller
    {
        private IServiceTypeRepository _repository;
        private IServiceTypeService _service;

        public ServiceTypeController()
        {
            const string connectionString = @"server=192.168.11.70\SQLEXPRESS,1433;database=abraham;uid=sa;password=toto;Application Name=Homer";

            _repository = new ServiceTypeRepository(connectionString);
            _service = new ServiceTypeService(_repository);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form(int? id)
        {
            if (id != null)
            {
                //edition
                var serviceType = _service.Get((int)id);
                return View(serviceType);
            }
            else
                //creation
                return View();

        }

        public ActionResult AddForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateServiceType(ServiceType model)
        {
            try
            {
                if (ModelState.IsValid)
                    model.Id = _service.Add(model);

            }
            catch (System.Exception)
            {
                throw;
            }

            return Content("{id:" + model.Id + "}");
        }

        [HttpPost]
        public ActionResult DescriptionExists(string description)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                    result = _service.DescriptionExists(description);
            }
            catch (System.Exception)
            {
                throw;
            }

            return Content($"{{\"state\":{result.ToString().ToLower()}}}");
        }
    }
}

Abraham/Abraham/Controllers/SessionController.cs
using Abraham.Domain.Business.Interfaces;
using Abraham.Domain.Business.Services;
using Abraham.Domain.Data.Interfaces;
using Abraham.Domain.Data.Repositories;
using System.Web.Mvc;

namespace Abraham.Controllers
{
    public class SessionController : Controller
    {
        private ISessionRepository _repository;
        private ISessionService _service;

        public SessionController()
        {
            const string connectionString = @"server=192.168.11.70\SQLEXPRESS,1433;database=abraham;uid=sa;password=toto;Application Name=Homer";

            _repository = new SessionRepository(connectionString);
            _service = new SessionService(_repository);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form(int id)
        {
            var session = _service.Get(id);


            return View(session);
        }
    }
}

Abraham/Abraham/Controllers/TimeBalanceController.cs
using Abraham.Domain.Business.Interfaces;
using Abraham.Domain.Business.Services;
using Abraham.Domain.Data.Interfaces;
using Abraham.Domain.Data.Repositories;
using System.Web.Mvc;

namespace Abraham.Controllers
{
    public class TimeBalanceController : Controller
    {
        private ITimeBalanceRepository _repository;
        private ITimeBalanceService _service;

        public TimeBalanceController()
        {
            const string connectionString = @"server=192.168.11.70\SQLEXPRESS,1433;database=abraham;uid=sa;password=toto;Application Name=Homer";

            _repository = new TimeBalanceRepository(connectionString);
            _service = new TimeBalanceService(_repository);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form(int id)
        {
            var tb = _service.Get(id);


            return View(tb);
        }
    }
}

Abraham/Abraham/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("User", "Index", "User")</li>
                    <li>@Html.ActionLink("User form", "Form", "User")</li>
                    <li>@Html.ActionLink("Session form", "Form", "Session")</li>
                    <li>@Html.ActionLink("Type de service", "Form", "ServiceType")</li>
                    <li>@Html.ActionLink("Service", "Form", "Service")</li>
                    <li>@Html.ActionLink("Computer form", "Form", "Computer")</li>
                    <li>@Html.ActionLink("Time balance", "Form", "TimeBalance")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Abraham/Abraham/Views/Shared/_LoginPartialView.cshtml
@model Abraham.Models.LoginViewModel

@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<section id="loginForm">
    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <h4>Use a local account to log in.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(m => m.RememberMe)
                    @Html.LabelFor(m => m.RememberMe)
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </div>
    }
</section>